-- Reinitialize tables
DROP TABLE IF EXISTS DEPENDENCY_RULES;
DROP TABLE IF EXISTS PROG_NAME;

-- Program Name Table
CREATE TABLE PROG_NAME
( UNIT_NBR       INT NOT NULL,
  STEP_SEQ_ID    INT NOT NULL,
  STEP_PROG_NAME VARCHAR,
  PRIMARY KEY (UNIT_NBR, STEP_SEQ_ID) );

-- Dependency Rules Table
CREATE TABLE DEPENDENCY_RULES
( UNIT_NBR    INT NOT NULL,
  RULE_ID     INT NOT NULL,
  STEP_SEQ_ID INT,
  STEP_DEP_ID INT,
  PRIMARY KEY (UNIT_NBR, RULE_ID),
  FOREIGN KEY (UNIT_NBR, STEP_SEQ_ID) REFERENCES PROG_NAME (UNIT_NBR, STEP_SEQ_ID) );
